product update method
---
tags:
  - Product
parameters:
  - name: id
    in: path
    required: true
    schema:
      type: integer
      minimum: 1
    description: The product ID
  - name: body

    description: The body should contain the product details
    in: body
    required: true
    schema:
      type: object

      properties:
        product_name:
          type: "string"
          example: "product_name"
        product_slug:
          type: "string"
          example: "product_slug"
        is_delete:
          type: "boolean"
          example: false
        price:
          type: integer
        old_price:
          type: integer
        item_stock:
          type: integer
        is_plan:
          type: "boolean"
          example: false
        category_id:
          type: integer


responses:
  201:
    description: When a product successfully update in

  400:
    description: Fails to update product